name: Top Players
main: com.pneumaticraft.highlander.Highlander
authors: ['fernferret']
version: maven-version-number
commands:
  hi:
    description: Generic Highlander Command
    usage: /<command>
  hih:
    description: Generic Highlander Command
    usage: /<command>
  hihelp:
    description: Generic Highlander Command
    usage: /<command>
  hisearch:
    description: Generic Highlander Command
    usage: /<command>
  hixp:
    description: Displays your xp and level.
    usage: /<command>
  hitop:
    description: There can be only one.
    usage: /<command>
